/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated/today'
import { Route as AuthenticatedSyllabusRouteImport } from './routes/_authenticated/syllabus'
import { Route as AuthenticatedStudyRoomsRouteImport } from './routes/_authenticated/study-rooms'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRevisionRouteImport } from './routes/_authenticated/revision'
import { Route as AuthenticatedResourcesRouteImport } from './routes/_authenticated/resources'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPracticeRouteImport } from './routes/_authenticated/practice'
import { Route as AuthenticatedPlannerRouteImport } from './routes/_authenticated/planner'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedHabitsRouteImport } from './routes/_authenticated/habits'
import { Route as AuthenticatedGoalsRouteImport } from './routes/_authenticated/goals'
import { Route as AuthenticatedFocusRouteImport } from './routes/_authenticated/focus'
import { Route as AuthenticatedErrorLogRouteImport } from './routes/_authenticated/error-log'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCutoffsRouteImport } from './routes/_authenticated/cutoffs'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAiCoachRouteImport } from './routes/_authenticated/ai-coach'
import { Route as AuthenticatedRevisionIndexRouteImport } from './routes/_authenticated/revision.index'
import { Route as AuthenticatedResourcesIndexRouteImport } from './routes/_authenticated/resources.index'
import { Route as AuthenticatedPracticeIndexRouteImport } from './routes/_authenticated/practice.index'
import { Route as AuthenticatedRevisionFlashcardsRouteImport } from './routes/_authenticated/revision.flashcards'
import { Route as AuthenticatedResourcesNotesRouteImport } from './routes/_authenticated/resources.notes'
import { Route as AuthenticatedResourcesNcertRouteImport } from './routes/_authenticated/resources.ncert'
import { Route as AuthenticatedResourcesDoubtsRouteImport } from './routes/_authenticated/resources.doubts'
import { Route as AuthenticatedPracticeResultsAttemptIdRouteImport } from './routes/_authenticated/practice.results.$attemptId'
import { Route as AuthenticatedPracticeLiveAttemptIdRouteImport } from './routes/_authenticated/practice.live.$attemptId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSyllabusRoute = AuthenticatedSyllabusRouteImport.update({
  id: '/syllabus',
  path: '/syllabus',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudyRoomsRoute = AuthenticatedStudyRoomsRouteImport.update({
  id: '/study-rooms',
  path: '/study-rooms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRevisionRoute = AuthenticatedRevisionRouteImport.update({
  id: '/revision',
  path: '/revision',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResourcesRoute = AuthenticatedResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPracticeRoute = AuthenticatedPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlannerRoute = AuthenticatedPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHabitsRoute = AuthenticatedHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFocusRoute = AuthenticatedFocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedErrorLogRoute = AuthenticatedErrorLogRouteImport.update({
  id: '/error-log',
  path: '/error-log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCutoffsRoute = AuthenticatedCutoffsRouteImport.update({
  id: '/cutoffs',
  path: '/cutoffs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiCoachRoute = AuthenticatedAiCoachRouteImport.update({
  id: '/ai-coach',
  path: '/ai-coach',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRevisionIndexRoute =
  AuthenticatedRevisionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRevisionRoute,
  } as any)
const AuthenticatedResourcesIndexRoute =
  AuthenticatedResourcesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedResourcesRoute,
  } as any)
const AuthenticatedPracticeIndexRoute =
  AuthenticatedPracticeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPracticeRoute,
  } as any)
const AuthenticatedRevisionFlashcardsRoute =
  AuthenticatedRevisionFlashcardsRouteImport.update({
    id: '/flashcards',
    path: '/flashcards',
    getParentRoute: () => AuthenticatedRevisionRoute,
  } as any)
const AuthenticatedResourcesNotesRoute =
  AuthenticatedResourcesNotesRouteImport.update({
    id: '/notes',
    path: '/notes',
    getParentRoute: () => AuthenticatedResourcesRoute,
  } as any)
const AuthenticatedResourcesNcertRoute =
  AuthenticatedResourcesNcertRouteImport.update({
    id: '/ncert',
    path: '/ncert',
    getParentRoute: () => AuthenticatedResourcesRoute,
  } as any)
const AuthenticatedResourcesDoubtsRoute =
  AuthenticatedResourcesDoubtsRouteImport.update({
    id: '/doubts',
    path: '/doubts',
    getParentRoute: () => AuthenticatedResourcesRoute,
  } as any)
const AuthenticatedPracticeResultsAttemptIdRoute =
  AuthenticatedPracticeResultsAttemptIdRouteImport.update({
    id: '/results/$attemptId',
    path: '/results/$attemptId',
    getParentRoute: () => AuthenticatedPracticeRoute,
  } as any)
const AuthenticatedPracticeLiveAttemptIdRoute =
  AuthenticatedPracticeLiveAttemptIdRouteImport.update({
    id: '/live/$attemptId',
    path: '/live/$attemptId',
    getParentRoute: () => AuthenticatedPracticeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/ai-coach': typeof AuthenticatedAiCoachRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/cutoffs': typeof AuthenticatedCutoffsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/error-log': typeof AuthenticatedErrorLogRoute
  '/focus': typeof AuthenticatedFocusRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/help': typeof AuthenticatedHelpRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/practice': typeof AuthenticatedPracticeRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/resources': typeof AuthenticatedResourcesRouteWithChildren
  '/revision': typeof AuthenticatedRevisionRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/study-rooms': typeof AuthenticatedStudyRoomsRoute
  '/syllabus': typeof AuthenticatedSyllabusRoute
  '/today': typeof AuthenticatedTodayRoute
  '/api/chat': typeof ApiChatRoute
  '/resources/doubts': typeof AuthenticatedResourcesDoubtsRoute
  '/resources/ncert': typeof AuthenticatedResourcesNcertRoute
  '/resources/notes': typeof AuthenticatedResourcesNotesRoute
  '/revision/flashcards': typeof AuthenticatedRevisionFlashcardsRoute
  '/practice/': typeof AuthenticatedPracticeIndexRoute
  '/resources/': typeof AuthenticatedResourcesIndexRoute
  '/revision/': typeof AuthenticatedRevisionIndexRoute
  '/practice/live/$attemptId': typeof AuthenticatedPracticeLiveAttemptIdRoute
  '/practice/results/$attemptId': typeof AuthenticatedPracticeResultsAttemptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/ai-coach': typeof AuthenticatedAiCoachRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/cutoffs': typeof AuthenticatedCutoffsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/error-log': typeof AuthenticatedErrorLogRoute
  '/focus': typeof AuthenticatedFocusRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/help': typeof AuthenticatedHelpRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/study-rooms': typeof AuthenticatedStudyRoomsRoute
  '/syllabus': typeof AuthenticatedSyllabusRoute
  '/today': typeof AuthenticatedTodayRoute
  '/api/chat': typeof ApiChatRoute
  '/resources/doubts': typeof AuthenticatedResourcesDoubtsRoute
  '/resources/ncert': typeof AuthenticatedResourcesNcertRoute
  '/resources/notes': typeof AuthenticatedResourcesNotesRoute
  '/revision/flashcards': typeof AuthenticatedRevisionFlashcardsRoute
  '/practice': typeof AuthenticatedPracticeIndexRoute
  '/resources': typeof AuthenticatedResourcesIndexRoute
  '/revision': typeof AuthenticatedRevisionIndexRoute
  '/practice/live/$attemptId': typeof AuthenticatedPracticeLiveAttemptIdRoute
  '/practice/results/$attemptId': typeof AuthenticatedPracticeResultsAttemptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/ai-coach': typeof AuthenticatedAiCoachRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/cutoffs': typeof AuthenticatedCutoffsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/error-log': typeof AuthenticatedErrorLogRoute
  '/_authenticated/focus': typeof AuthenticatedFocusRoute
  '/_authenticated/goals': typeof AuthenticatedGoalsRoute
  '/_authenticated/habits': typeof AuthenticatedHabitsRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/planner': typeof AuthenticatedPlannerRoute
  '/_authenticated/practice': typeof AuthenticatedPracticeRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/resources': typeof AuthenticatedResourcesRouteWithChildren
  '/_authenticated/revision': typeof AuthenticatedRevisionRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/study-rooms': typeof AuthenticatedStudyRoomsRoute
  '/_authenticated/syllabus': typeof AuthenticatedSyllabusRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/resources/doubts': typeof AuthenticatedResourcesDoubtsRoute
  '/_authenticated/resources/ncert': typeof AuthenticatedResourcesNcertRoute
  '/_authenticated/resources/notes': typeof AuthenticatedResourcesNotesRoute
  '/_authenticated/revision/flashcards': typeof AuthenticatedRevisionFlashcardsRoute
  '/_authenticated/practice/': typeof AuthenticatedPracticeIndexRoute
  '/_authenticated/resources/': typeof AuthenticatedResourcesIndexRoute
  '/_authenticated/revision/': typeof AuthenticatedRevisionIndexRoute
  '/_authenticated/practice/live/$attemptId': typeof AuthenticatedPracticeLiveAttemptIdRoute
  '/_authenticated/practice/results/$attemptId': typeof AuthenticatedPracticeResultsAttemptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/ai-coach'
    | '/analytics'
    | '/calendar'
    | '/cutoffs'
    | '/dashboard'
    | '/error-log'
    | '/focus'
    | '/goals'
    | '/habits'
    | '/help'
    | '/notifications'
    | '/planner'
    | '/practice'
    | '/profile'
    | '/resources'
    | '/revision'
    | '/settings'
    | '/study-rooms'
    | '/syllabus'
    | '/today'
    | '/api/chat'
    | '/resources/doubts'
    | '/resources/ncert'
    | '/resources/notes'
    | '/revision/flashcards'
    | '/practice/'
    | '/resources/'
    | '/revision/'
    | '/practice/live/$attemptId'
    | '/practice/results/$attemptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/ai-coach'
    | '/analytics'
    | '/calendar'
    | '/cutoffs'
    | '/dashboard'
    | '/error-log'
    | '/focus'
    | '/goals'
    | '/habits'
    | '/help'
    | '/notifications'
    | '/planner'
    | '/profile'
    | '/settings'
    | '/study-rooms'
    | '/syllabus'
    | '/today'
    | '/api/chat'
    | '/resources/doubts'
    | '/resources/ncert'
    | '/resources/notes'
    | '/revision/flashcards'
    | '/practice'
    | '/resources'
    | '/revision'
    | '/practice/live/$attemptId'
    | '/practice/results/$attemptId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/_authenticated/ai-coach'
    | '/_authenticated/analytics'
    | '/_authenticated/calendar'
    | '/_authenticated/cutoffs'
    | '/_authenticated/dashboard'
    | '/_authenticated/error-log'
    | '/_authenticated/focus'
    | '/_authenticated/goals'
    | '/_authenticated/habits'
    | '/_authenticated/help'
    | '/_authenticated/notifications'
    | '/_authenticated/planner'
    | '/_authenticated/practice'
    | '/_authenticated/profile'
    | '/_authenticated/resources'
    | '/_authenticated/revision'
    | '/_authenticated/settings'
    | '/_authenticated/study-rooms'
    | '/_authenticated/syllabus'
    | '/_authenticated/today'
    | '/api/chat'
    | '/_authenticated/resources/doubts'
    | '/_authenticated/resources/ncert'
    | '/_authenticated/resources/notes'
    | '/_authenticated/revision/flashcards'
    | '/_authenticated/practice/'
    | '/_authenticated/resources/'
    | '/_authenticated/revision/'
    | '/_authenticated/practice/live/$attemptId'
    | '/_authenticated/practice/results/$attemptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/syllabus': {
      id: '/_authenticated/syllabus'
      path: '/syllabus'
      fullPath: '/syllabus'
      preLoaderRoute: typeof AuthenticatedSyllabusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/study-rooms': {
      id: '/_authenticated/study-rooms'
      path: '/study-rooms'
      fullPath: '/study-rooms'
      preLoaderRoute: typeof AuthenticatedStudyRoomsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/revision': {
      id: '/_authenticated/revision'
      path: '/revision'
      fullPath: '/revision'
      preLoaderRoute: typeof AuthenticatedRevisionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resources': {
      id: '/_authenticated/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthenticatedResourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice': {
      id: '/_authenticated/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof AuthenticatedPracticeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planner': {
      id: '/_authenticated/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AuthenticatedPlannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/habits': {
      id: '/_authenticated/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof AuthenticatedHabitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/focus': {
      id: '/_authenticated/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof AuthenticatedFocusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/error-log': {
      id: '/_authenticated/error-log'
      path: '/error-log'
      fullPath: '/error-log'
      preLoaderRoute: typeof AuthenticatedErrorLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cutoffs': {
      id: '/_authenticated/cutoffs'
      path: '/cutoffs'
      fullPath: '/cutoffs'
      preLoaderRoute: typeof AuthenticatedCutoffsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-coach': {
      id: '/_authenticated/ai-coach'
      path: '/ai-coach'
      fullPath: '/ai-coach'
      preLoaderRoute: typeof AuthenticatedAiCoachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/revision/': {
      id: '/_authenticated/revision/'
      path: '/'
      fullPath: '/revision/'
      preLoaderRoute: typeof AuthenticatedRevisionIndexRouteImport
      parentRoute: typeof AuthenticatedRevisionRoute
    }
    '/_authenticated/resources/': {
      id: '/_authenticated/resources/'
      path: '/'
      fullPath: '/resources/'
      preLoaderRoute: typeof AuthenticatedResourcesIndexRouteImport
      parentRoute: typeof AuthenticatedResourcesRoute
    }
    '/_authenticated/practice/': {
      id: '/_authenticated/practice/'
      path: '/'
      fullPath: '/practice/'
      preLoaderRoute: typeof AuthenticatedPracticeIndexRouteImport
      parentRoute: typeof AuthenticatedPracticeRoute
    }
    '/_authenticated/revision/flashcards': {
      id: '/_authenticated/revision/flashcards'
      path: '/flashcards'
      fullPath: '/revision/flashcards'
      preLoaderRoute: typeof AuthenticatedRevisionFlashcardsRouteImport
      parentRoute: typeof AuthenticatedRevisionRoute
    }
    '/_authenticated/resources/notes': {
      id: '/_authenticated/resources/notes'
      path: '/notes'
      fullPath: '/resources/notes'
      preLoaderRoute: typeof AuthenticatedResourcesNotesRouteImport
      parentRoute: typeof AuthenticatedResourcesRoute
    }
    '/_authenticated/resources/ncert': {
      id: '/_authenticated/resources/ncert'
      path: '/ncert'
      fullPath: '/resources/ncert'
      preLoaderRoute: typeof AuthenticatedResourcesNcertRouteImport
      parentRoute: typeof AuthenticatedResourcesRoute
    }
    '/_authenticated/resources/doubts': {
      id: '/_authenticated/resources/doubts'
      path: '/doubts'
      fullPath: '/resources/doubts'
      preLoaderRoute: typeof AuthenticatedResourcesDoubtsRouteImport
      parentRoute: typeof AuthenticatedResourcesRoute
    }
    '/_authenticated/practice/results/$attemptId': {
      id: '/_authenticated/practice/results/$attemptId'
      path: '/results/$attemptId'
      fullPath: '/practice/results/$attemptId'
      preLoaderRoute: typeof AuthenticatedPracticeResultsAttemptIdRouteImport
      parentRoute: typeof AuthenticatedPracticeRoute
    }
    '/_authenticated/practice/live/$attemptId': {
      id: '/_authenticated/practice/live/$attemptId'
      path: '/live/$attemptId'
      fullPath: '/practice/live/$attemptId'
      preLoaderRoute: typeof AuthenticatedPracticeLiveAttemptIdRouteImport
      parentRoute: typeof AuthenticatedPracticeRoute
    }
  }
}

interface AuthenticatedPracticeRouteChildren {
  AuthenticatedPracticeIndexRoute: typeof AuthenticatedPracticeIndexRoute
  AuthenticatedPracticeLiveAttemptIdRoute: typeof AuthenticatedPracticeLiveAttemptIdRoute
  AuthenticatedPracticeResultsAttemptIdRoute: typeof AuthenticatedPracticeResultsAttemptIdRoute
}

const AuthenticatedPracticeRouteChildren: AuthenticatedPracticeRouteChildren = {
  AuthenticatedPracticeIndexRoute: AuthenticatedPracticeIndexRoute,
  AuthenticatedPracticeLiveAttemptIdRoute:
    AuthenticatedPracticeLiveAttemptIdRoute,
  AuthenticatedPracticeResultsAttemptIdRoute:
    AuthenticatedPracticeResultsAttemptIdRoute,
}

const AuthenticatedPracticeRouteWithChildren =
  AuthenticatedPracticeRoute._addFileChildren(
    AuthenticatedPracticeRouteChildren,
  )

interface AuthenticatedResourcesRouteChildren {
  AuthenticatedResourcesDoubtsRoute: typeof AuthenticatedResourcesDoubtsRoute
  AuthenticatedResourcesNcertRoute: typeof AuthenticatedResourcesNcertRoute
  AuthenticatedResourcesNotesRoute: typeof AuthenticatedResourcesNotesRoute
  AuthenticatedResourcesIndexRoute: typeof AuthenticatedResourcesIndexRoute
}

const AuthenticatedResourcesRouteChildren: AuthenticatedResourcesRouteChildren =
  {
    AuthenticatedResourcesDoubtsRoute: AuthenticatedResourcesDoubtsRoute,
    AuthenticatedResourcesNcertRoute: AuthenticatedResourcesNcertRoute,
    AuthenticatedResourcesNotesRoute: AuthenticatedResourcesNotesRoute,
    AuthenticatedResourcesIndexRoute: AuthenticatedResourcesIndexRoute,
  }

const AuthenticatedResourcesRouteWithChildren =
  AuthenticatedResourcesRoute._addFileChildren(
    AuthenticatedResourcesRouteChildren,
  )

interface AuthenticatedRevisionRouteChildren {
  AuthenticatedRevisionFlashcardsRoute: typeof AuthenticatedRevisionFlashcardsRoute
  AuthenticatedRevisionIndexRoute: typeof AuthenticatedRevisionIndexRoute
}

const AuthenticatedRevisionRouteChildren: AuthenticatedRevisionRouteChildren = {
  AuthenticatedRevisionFlashcardsRoute: AuthenticatedRevisionFlashcardsRoute,
  AuthenticatedRevisionIndexRoute: AuthenticatedRevisionIndexRoute,
}

const AuthenticatedRevisionRouteWithChildren =
  AuthenticatedRevisionRoute._addFileChildren(
    AuthenticatedRevisionRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiCoachRoute: typeof AuthenticatedAiCoachRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedCutoffsRoute: typeof AuthenticatedCutoffsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedErrorLogRoute: typeof AuthenticatedErrorLogRoute
  AuthenticatedFocusRoute: typeof AuthenticatedFocusRoute
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRoute
  AuthenticatedHabitsRoute: typeof AuthenticatedHabitsRoute
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPlannerRoute: typeof AuthenticatedPlannerRoute
  AuthenticatedPracticeRoute: typeof AuthenticatedPracticeRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedResourcesRoute: typeof AuthenticatedResourcesRouteWithChildren
  AuthenticatedRevisionRoute: typeof AuthenticatedRevisionRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStudyRoomsRoute: typeof AuthenticatedStudyRoomsRoute
  AuthenticatedSyllabusRoute: typeof AuthenticatedSyllabusRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiCoachRoute: AuthenticatedAiCoachRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedCutoffsRoute: AuthenticatedCutoffsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedErrorLogRoute: AuthenticatedErrorLogRoute,
  AuthenticatedFocusRoute: AuthenticatedFocusRoute,
  AuthenticatedGoalsRoute: AuthenticatedGoalsRoute,
  AuthenticatedHabitsRoute: AuthenticatedHabitsRoute,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPlannerRoute: AuthenticatedPlannerRoute,
  AuthenticatedPracticeRoute: AuthenticatedPracticeRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedResourcesRoute: AuthenticatedResourcesRouteWithChildren,
  AuthenticatedRevisionRoute: AuthenticatedRevisionRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStudyRoomsRoute: AuthenticatedStudyRoomsRoute,
  AuthenticatedSyllabusRoute: AuthenticatedSyllabusRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
